2021-07-17T14:44:08.392907+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:14:08,392] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T14:44:55.177792+00:00 app[ultroid.1]: [ERROR/2021-07-17 20:14:55,176] telethon.client.updates: Unhandled exception on query_ibutton
2021-07-17T14:44:55.177811+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-17T14:44:55.177812+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 454, in _dispatch_update
2021-07-17T14:44:55.177813+00:00 app[ultroid.1]:     await callback(event)
2021-07-17T14:44:55.177814+00:00 app[ultroid.1]:   File "/root/TeamUltroid/addons/button.py", line 106, in query_ibutton
2021-07-17T14:44:55.177815+00:00 app[ultroid.1]:     await event.answer([result] if result else None)
2021-07-17T14:44:55.177816+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/inlinequery.py", line 221, in answer
2021-07-17T14:44:55.177816+00:00 app[ultroid.1]:     results = [x.result() for x in futures]
2021-07-17T14:44:55.177817+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/events/inlinequery.py", line 221, in <listcomp>
2021-07-17T14:44:55.177817+00:00 app[ultroid.1]:     results = [x.result() for x in futures]
2021-07-17T14:44:55.177817+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/inlinebuilder.py", line 132, in article
2021-07-17T14:44:55.177818+00:00 app[ultroid.1]:     send_message=await self._message(
2021-07-17T14:44:55.177818+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/inlinebuilder.py", line 382, in _message
2021-07-17T14:44:55.177818+00:00 app[ultroid.1]:     raise ValueError(
2021-07-17T14:44:55.177819+00:00 app[ultroid.1]: ValueError: Must set exactly one of text, geo, contact or game (set none)
2021-07-17T14:54:28.937741+00:00 app[ultroid.1]: [WARNING/2021-07-17 20:24:28,937] telethon.client.users: Telegram is having internal issues HistoryGetFailedError: Fetching of history failed (caused by GetChannelDifferenceRequest)
2021-07-17T14:54:35.523928+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:24:35,523] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T14:56:08.544385+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:26:08,544] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T14:56:42.660375+00:00 app[ultroid.1]: [WARNING/2021-07-17 20:26:42,659] py.warnings: /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'virginia.sessions.logs.heroku.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-17T14:56:42.660384+00:00 app[ultroid.1]:   warnings.warn(
2021-07-17T14:56:42.660386+00:00 app[ultroid.1]: 
2021-07-17T14:56:42.756210+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:26:42,755] telethon.client.uploads: Uploading file of 15102 bytes in 1 chunks of 131072
2021-07-17T15:01:07.347250+00:00 app[ultroid.1]: [WARNING/2021-07-17 20:31:07,346] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:01:33.152031+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:31:33,151] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T15:02:04.248815+00:00 app[ultroid.1]: [WARNING/2021-07-17 20:32:04,248] py.warnings: /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'virginia.sessions.logs.heroku.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-17T15:02:04.248827+00:00 app[ultroid.1]:   warnings.warn(
2021-07-17T15:02:04.248828+00:00 app[ultroid.1]: 
2021-07-17T15:02:04.325490+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:32:04,325] telethon.client.uploads: Uploading file of 15138 bytes in 1 chunks of 131072
2021-07-17T15:08:39.211199+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:38:39,210] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T15:08:50.149061+00:00 app[ultroid.1]: [ERROR/2021-07-17 20:38:50,148] pyUltroid: local variable 'reply_msg' referenced before assignment
2021-07-17T15:08:50.149072+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-17T15:08:50.149072+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/pyUltroid/misc/_decorators.py", line 99, in wrapper
2021-07-17T15:08:50.149073+00:00 app[ultroid.1]:     await func(ult)
2021-07-17T15:08:50.149074+00:00 app[ultroid.1]:   File "/root/TeamUltroid/addons/btn.py", line 123, in ibutton
2021-07-17T15:08:50.149074+00:00 app[ultroid.1]:     if reply_msg:
2021-07-17T15:08:50.149075+00:00 app[ultroid.1]: UnboundLocalError: local variable 'reply_msg' referenced before assignment
2021-07-17T15:12:26.975350+00:00 app[ultroid.1]: [ERROR/2021-07-17 20:42:26,974] pyUltroid: local variable 'ok' referenced before assignment
2021-07-17T15:12:26.975360+00:00 app[ultroid.1]: Traceback (most recent call last):
2021-07-17T15:12:26.975361+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/pyUltroid/misc/_decorators.py", line 99, in wrapper
2021-07-17T15:12:26.975362+00:00 app[ultroid.1]:     await func(ult)
2021-07-17T15:12:26.975363+00:00 app[ultroid.1]:   File "/root/TeamUltroid/plugins/core.py", line 40, in install
2021-07-17T15:12:26.975363+00:00 app[ultroid.1]:     await safeinstall(event)
2021-07-17T15:12:26.975364+00:00 app[ultroid.1]:   File "/usr/local/lib/python3.9/site-packages/pyUltroid/functions/all.py", line 1329, in safeinstall
2021-07-17T15:12:26.975365+00:00 app[ultroid.1]:     await ok.edit(f"Please use `{HNDLR}install` as reply to a .py file.")
2021-07-17T15:12:26.975365+00:00 app[ultroid.1]: UnboundLocalError: local variable 'ok' referenced before assignment
2021-07-17T15:12:31.574108+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:42:31,573] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T15:25:00.092462+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,092] telethon.network.mtprotosender: Connecting to 149.154.175.57:443/TcpFull...
2021-07-17T15:25:00.138419+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,138] telethon.network.mtprotosender: Connection to 149.154.175.57:443/TcpFull complete!
2021-07-17T15:25:00.355869+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,355] telethon.network.mtprotosender: Disconnecting from 149.154.175.57:443/TcpFull...
2021-07-17T15:25:00.375522+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,375] telethon.network.mtprotosender: Disconnection from 149.154.175.57:443/TcpFull complete!
2021-07-17T15:25:00.380757+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,380] telethon.network.mtprotosender: Connecting to 149.154.175.57:443/TcpFull...
2021-07-17T15:25:00.419309+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:00,419] telethon.network.mtprotosender: Connection to 149.154.175.57:443/TcpFull complete!
2021-07-17T15:25:01.072018+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:01,071] telethon.network.mtprotosender: Disconnecting from 149.154.175.57:443/TcpFull...
2021-07-17T15:25:01.072900+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:01,072] telethon.network.mtprotosender: Disconnection from 149.154.175.57:443/TcpFull complete!
2021-07-17T15:25:01.076718+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:55:01,075] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-17T15:28:00.730245+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:58:00,726] telethon.network.mtprotosender: Connecting to 149.154.175.57:443/TcpFull...
2021-07-17T15:28:00.763150+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:58:00,762] telethon.network.mtprotosender: Connection to 149.154.175.57:443/TcpFull complete!
2021-07-17T15:28:01.760634+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:58:01,756] telethon.network.mtprotosender: Disconnecting from 149.154.175.57:443/TcpFull...
2021-07-17T15:28:01.765064+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:58:01,763] telethon.network.mtprotosender: Disconnection from 149.154.175.57:443/TcpFull complete!
2021-07-17T15:28:01.790549+00:00 app[ultroid.1]: [ INFO/2021-07-17 20:58:01,790] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-17T15:30:20.719821+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:00:20,719] telethon.client.uploads: Uploading file of 7438 bytes in 1 chunks of 131072
2021-07-17T15:30:20.789027+00:00 app[ultroid.1]: Getting Connection With Redis Database
2021-07-17T15:30:20.789030+00:00 app[ultroid.1]: Succesfully Established Connection With Redis DataBase.
2021-07-17T15:30:20.789030+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789030+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789031+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789031+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789032+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789032+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789032+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789033+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789033+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789033+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789034+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789034+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789035+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789035+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789035+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789036+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789036+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789037+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789037+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789037+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789038+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789038+00:00 app[ultroid.1]: 'NoneType' object has no attribute 'format'
2021-07-17T15:30:20.789085+00:00 app[ultroid.1]: [warn] [<NdsFile>] Error when getting size of 'header': delete it
2021-07-17T15:30:20.790374+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:00:20,790] telethon.client.uploads: Uploading file of 48325 bytes in 1 chunks of 131072
2021-07-17T15:37:25.331349+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:07:25,330] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:37:25.336314+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:07:25,336] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:37:27.402759+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:07:27,402] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:37:29.452398+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:07:29,451] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:37:31.601728+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:07:31,601] telethon.client.users: Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)
2021-07-17T15:42:58.066835+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:12:58,066] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
2021-07-17T15:48:30.630306+00:00 app[ultroid.1]: [WARNING/2021-07-17 21:18:30,629] py.warnings: /usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'virginia.sessions.logs.heroku.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-07-17T15:48:30.632744+00:00 app[ultroid.1]:   warnings.warn(
2021-07-17T15:48:30.632746+00:00 app[ultroid.1]: 
2021-07-17T15:48:30.716098+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:18:30,715] telethon.client.uploads: Uploading file of 13545 bytes in 1 chunks of 131072
2021-07-17T15:57:05.219951+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:27:05,219] telethon.client.uploads: Uploading file of 36214 bytes in 1 chunks of 131072
2021-07-17T16:06:46.239887+00:00 app[ultroid.1]: [ INFO/2021-07-17 21:36:46,239] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
